---

- name: Create dirs
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.user | default(default_user) }}'
    group: '{{ item.group | default(default_user) }}'
    mode: '{{ item.mode | default("0755") }}'
    recurse: true
  loop:
    - path: '{{ docker_container_data_folder }}/orca/onedrive_conf'
      owner: '{{ default_user }}'
      group: '{{ default_user }}'
      mode: '0700'
    - path: '{{ docker_container_data_folder }}/orca/onedrive'
      owner: '{{ default_user }}'
      group: '{{ default_user }}'
      mode: '0700'
    - path: '/home/{{ default_user }}/docker/orca/'
  become: true

- name: Create configure script
  ansible.builtin.template:
    src: docker01/configure_onedrive.sh.j2
    dest: '/home/{{ default_user }}/docker/orca/configure_onedrive.sh'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

- name: Create compose file
  ansible.builtin.template:
    src: docker01/orca_stack.yml.j2
    dest: '/home/{{ default_user }}/docker/orca/docker-compose.yml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

# Check if config exists
- name: Check for config
  ansible.builtin.stat:
    path: '/home/{{ default_user }}/docker/orca/configured'
  register: configfile

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/orca/'
  when: configfile.stat.exists

- name: Run configure script
  ansible.builtin.debug:
    msg: "Please run the configure script!"
  when: not configfile.stat.exists
