---

# Periphery
docker_periphery_github_url: https://api.github.com/repos/moghtech/komodo/releases/latest
docker_periphery_version_file: /opt/periphery.txt

docker_komodo_bin_path: '/home/{{ default_user }}/.local/bin/periphery'
docker_komodo_config_path: '/home/{{ default_user }}/.config/komodo'
