---

# Baisc host settings
host_name: harald
host_ip: 192.168.20.30
host_gateway: 192.168.20.1
host_subnet: /24
host_vlan: 20

# LXC settings
lxc_data:
  vmid: 120
  node: "pikachu"
  cores: 2
  memory: 4096
  disk: 'zfs:20'
  netif:
    net0: "name=eth0,gw={{ host_gateway }},ip={{ host_ip }}{{ host_subnet }},bridge=vmbr0,firewall=0,tag={{ host_vlan }}"

# Reverse Proxy settings
proxy:
  - name: '{{ host_name }}'
    hostname: '{{ host_name }}.berger-em.net'
    proxy_host: 'http://{{ host_ip }}'
